[package]
name = "energymon"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
rumqttc = "0.24"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = "4"
